module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#191c1d',
        'secondary-container': '#fda141',
        'primary-fixed': '#aaeef4',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#b0cadd',
        'on-error-container': '#93000a',
        'on-surface-variant': '#3f4849',
        'on-tertiary-container': '#b3cde1',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        secondary: '#8d4f00',
        'on-secondary-fixed-variant': '#6b3b00',
        'error-container': '#ffdad6',
        tertiary: '#274150',
        'tertiary-container': '#3f5868',
        'on-tertiary-fixed': '#011e2d',
        'secondary-fixed-dim': '#ffb876',
        'outline-variant': '#bec8c9',
        background: '#f8f9fa',
        'inverse-surface': '#2e3132',
        surface: '#f8f9fa',
        'on-secondary-container': '#6c3b00',
        'on-primary-fixed': '#002022',
        'on-surface': '#191c1d',
        'surface-variant': '#e1e3e4',
        'inverse-primary': '#8ed2d7',
        primary: '#004549',
        outline: '#6f7979',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-highest': '#e1e3e4',
        'on-primary': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'on-secondary-fixed': '#2d1600',
        'primary-container': '#0d5e63',
        'surface-tint': '#1e686d',
        'surface-dim': '#d9dadb',
        'surface-container': '#edeeef',
        'on-primary-container': '#91d5da',
        'tertiary-fixed': '#cce6fa',
        'primary-fixed-dim': '#8ed2d7',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#314a5a',
        'on-primary-fixed-variant': '#004f54',
        'secondary-fixed': '#ffdcc0',
        'surface-container-low': '#f3f4f5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'container-margin': '16px',
        base: '8px',
        'section-gap': '32px',
        'card-padding': '20px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'data-numeric': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'data-numeric': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
      },
    },
  },
};
